### PR TITLE
Fixes #807

### LINKED ISSUE #807: Make `AppMetrics.push` safe when pushgateway is unavailable
Just noticed this running ingestion locally without a push gateway up:

```
[ ERROR ] NIOConnectionError(host: "127.0.0.1", port: 9091, dnsAError: nil, dnsAAAAError: nil, connectionErrors: [NIO.SingleConnectionFailure(target: [IPv4]127.0.0.1/127.0.0.1:9091, error: connection reset (error set): Connection refused (errno: 61))])
Fatal error: Error raised at top level: NIO.NIOConnectionError(host: "127.0.0.1", port: 9091, dnsAError: nil, dnsAAAAError: nil, connectionErrors: [NIO.SingleConnectionFailure(target: [IPv4]127.0.0.1/127.0.0.1:9091, error: connection reset (error set): Connection refused (errno: 61))]): file Swift/ErrorType.swift, line 200
2020-11-24 06:51:48.820471+0100 Run[10935:165262] Fatal error: Error raised at top level: NIO.NIOConnectionError(host: "127.0.0.1", port: 9091, dnsAError: nil, dnsAAAAError: nil, connectionErrors: [NIO.SingleConnectionFailure(target: [IPv4]127.0.0.1/127.0.0.1:9091, error: connection reset (error set): Connection refused (errno: 61))]): file Swift/ErrorType.swift, line 200
```

### PR DESCRIPTION
**Pull request by finestructure**
Logging error instead:

```
Ingesting (id: F2D88142-0017-4B75-AB17-2FD29E1E75F7) ...
[ ERROR ] AppMetrics.push failed with error: NIOConnectionError(host: "127.0.0.1", port: 9091, dnsAError: nil, dnsAAAAError: nil, connectionErrors: [NIO.SingleConnectionFailure(target: [IPv4]127.0.0.1/127.0.0.1:9091, error: connection reset (error set): Connection refused (errno: 61))])
```

### CODE REVIEW

File: Sources/App/Commands/Analyzer.swift [hunk 1]
```diff
@@ -76,7 +77,7 @@ func analyze(application: Application, packages: [Package]) -> EventLoopFuture<V
                                                     withIntermediateDirectories: false,
                                                     attributes: nil)
         } catch {
-            let msg = "Failed to create checkouts directory: \(error.localizedDescription)"
+            let msg = "Failed to create checkouts directory: \(error)"
```
Comment (finestructure) [inline Sources/App/Commands/Analyzer.swift:80]: I initially also used `error.localizedDescription` for reporting the `AppMetrics.push` error but noticed that that prints

```
The operation couldn’t be completed. (NIO.NIOConnectionError error 1.)
```

vs

```
NIOConnectionError(host: "127.0.0.1", port: 9091, dnsAError: nil, dnsAAAAError: nil, connectionErrors: 
[NIO.SingleConnectionFailure(target: [IPv4]127.0.0.1/127.0.0.1:9091, error: connection reset (error set): 
Connection refused (errno: 61))])
```

when it's `"\(error)"`. I wonder if we'd get a lot more error detail in our rollbar items this way, so I propose we give that a try.

Comment (finestructure) [reply Sources/App/Commands/Analyzer.swift]: I've reverted this for now, because it also changes

```
[ ERROR ] ingestion error: missing Github API token [database-id: psql]
```

to

```
[ ERROR ] ingestion error: missingToken [database-id: psql]
```

for our on `LocalizedError`s. Best not mix this in here and look into this separately. In the past I've used https://swiftpackageindex.com/mxcl/LegibleError to get better error printouts and it might be a good idea to use that.

**Review by daveverwer — APPROVED** [review]
