### PR TITLE
Fix recent links, add test

### LINKED ISSUE #185: Fix recent packages/releases links

### PR DESCRIPTION
**Pull request by finestructure**
Fixes #185

### CODE REVIEW

File: Sources/App/Views/Home/HomeIndex+Query.swift [hunk 1]
```diff
@@ -13,11 +13,11 @@ extension HomeIndex.Model {
 
 extension HomeIndex.Model {
     static func makeLink(_ recent: RecentPackage) -> Link {
-        return .init(label: recent.packageName, url: "/packages\(recent.id.uuidString)")
+        return .init(label: recent.packageName, url: "/packages/\(recent.id.uuidString)")
```
Comment (daveverwer) [inline Sources/App/Views/Home/HomeIndex+Query.swift:16]: I was about to add this as an issue! 😂
