### PR TITLE
Fixes the HTML XSS vulnerability

### LINKED ISSUE #1409: Speech mark splits search input
**Please describe the bug**

If your search query includes a speech mark, then everything after (and including) the speech mark is then seemingly lost in the search box.

**Explain the steps needed to reproduce the bug**

1. Navigate to to https://swiftpackageindex.com/search?query=test+%22+two
3. See that the 'results for' section includes the full string, but the search box only has the the string before the speech mark.

**What was the expected behaviour?**

The search box should include the full query input string.

**Screenshots**

Screenshot 2021-12-01 at 2 05 23 pm

**What web browser were you using? (if relevant)**

- Platform: Desktop
- Browser: Chrome

### LINKED ISSUE #2206: XSS vulnerability
https://www.openbugbounty.org/reports/3128202/

### PR DESCRIPTION
**Pull request by daveverwer**
Fixes #2206 
Fixes #1409

This ended up fixing #1409 too, as it was exercising the same code in a much less malicious way 😂

### CODE REVIEW

File: Sources/App/Views/Search/SearchShow+Model.swift [hunk 1]
```diff
@@ -68,3 +68,16 @@ enum SearchShow {
...
+
+extension String {
+    func filteredForDisplay() -> String {
+        // This does not strip HTML tags as it's possible people would want to search for them.
+        // Instead, it changes angle brackets and quotes and when combined with our SQL sanitisation does everything we need.
+        self.replacingOccurrences(of: ">", with: "&gt;")
+            .replacingOccurrences(of: "<", with: "&lt;")
+            .replacingOccurrences(of: "'", with: "&apos;")
+            .replacingOccurrences(of: "\"", with: "&quot;")
+        // Also, the `term` coming back out of the view model may contain backslash escape characters which we should not display.
```
Comment (daveverwer) [inline Sources/App/Views/Search/SearchShow+Model.swift:80]: This is actually an unrelated fix. On the current site, if you search for anything that gets sanitised as part of `Search.sanitize`, the escape character was being echoed back to the output in HTML.

Unrelated fix, but worth doing at the same time!

File: Sources/App/Views/Search/SearchShow+Model.swift [hunk 2]
```diff
@@ -24,8 +24,8 @@ enum SearchShow {
 
         internal init(page: Int, query: String, response: Search.Response, weightedKeywords: [WeightedKeyword]) {
             self.page = page
-            self.query = query
-            self.term = response.searchTerm
+            self.query = query.filteredForDisplay()
+            self.term = response.searchTerm.filteredForDisplay()
```
Comment (finestructure) [inline Sources/App/Views/Search/SearchShow+Model.swift:28]: I think it would be important to have some regression tests for this in place, in particular the actual offending string and what it looks like after.

Comment (finestructure) [reply Sources/App/Views/Search/SearchShow+Model.swift:28]: Just on the SearchShow init should be enough as it's the general entrypoint I think.

Comment (daveverwer) [reply Sources/App/Views/Search/SearchShow+Model.swift:28]: Good idea. I made it a snapshot test because the exploit injected an SVG which also broke the layout so it should verify that nothing changes visually, too.

File: Sources/App/Views/Search/SearchShow+Model.swift [hunk 3]
```diff
@@ -68,3 +68,16 @@ enum SearchShow {
     }
 
 }
+
+extension String {
+    func filteredForDisplay() -> String {
```
Comment (finestructure) [inline Sources/App/Views/Search/SearchShow+Model.swift:73]: Nit: I'd call this `sanitized()` instead, matching out `Search.sanitize()` function.

**Review by finestructure — APPROVED** [review]

**Comment by daveverwer** [comment]
Deploying as 2.79.26
