### PR TITLE
Fix new package tweets

### LINKED ISSUE #802: Package.isNew not behaving as expected
Screenshot 2020-11-21 at 09 42 55

### PR DESCRIPTION
**Pull request by finestructure**
Fixes #802

### CODE REVIEW

File: Sources/App/Models/Package.swift [hunk 1]
```diff
@@ -78,7 +78,7 @@ extension Package {
         case analysis
     }
 
-    var isNew: Bool { processingStage != .analysis }
+    var isNew: Bool { status == .new }
```
Comment (finestructure) [inline Sources/App/Models/Package.swift:81]: I was done adding the new field and wiring it up when I discovered this in `updatePackage` - where a I was going to reset `isNew`:

```swift
                        if stage == .ingestion && pkg.status == .new {
                            // newly ingested package: leave status == .new for fast-track
                            // analysis
                        } else {
```

🤦 

Still want to double check everything tomorrow but I think this will be all that's needed. Tests all pass, so that's a good sign

Comment (daveverwer) [reply Sources/App/Models/Package.swift:81]: Thanks, past-Sven! 😅

**Review by daveverwer — APPROVED** [review]
