### PR TITLE
Lowercased all documentation path components in S3 URLs

### LINKED ISSUE #1774: Doc link broken due to case discrepancy
The doc link we generate is: https://swiftpackageindex.com/Sherlouk/SpanGrid/main/documentation/spangrid

The S3 URL is: https://swiftpackageindex.com/sherlouk/SpanGrid/main/documentation/spangrid

I'm not sure where the transformation is happening and why - we're not touching the case of the owner or repo name normally.

cc @Sherlouk

### PR DESCRIPTION
**Pull request by daveverwer**
Fixes #1774

### CODE REVIEW

File: Sources/App/Controllers/PackageController+routes.swift [hunk 1]
```diff
@@ -280,7 +280,9 @@ extension PackageController {
             throw AppError.envVariableNotSet("AWS_DOCS_BUCKET")
         }
 
-        let baseURL = "http://\(bucket).s3-website.us-east-2.amazonaws.com/\(owner)/\(repository)/\(reference)"
+        let baseURLHost = "\(bucket).s3-website.us-east-2.amazonaws.com"
+        let baseURLPath = "\(owner.lowercased())/\(repository.lowercased())/\(reference.lowercased())"
+        let baseURL = "http://\(baseURLHost)/\(baseURLPath)"
```
Comment (daveverwer) [inline Sources/App/Controllers/PackageController+routes.swift:285]: I know we could just lowercase the resulting `baseURL`, but lowercasing each part felt better as it expresses the intention of this change better.

**Review by finestructure — APPROVED** [review]
