### PR TITLE
Issue 58 git prompt crash

### LINKED ISSUE #58: `GIT_TERMINAL_PROMPT=0` leads to crash on Linux
Triggering repository is our friend https://github.com/SwiftyBeaver/AES256CBC.git

```
analyze_1    | Fatal error: Error raised at top level: ShellOut encountered an error
analyze_1    | Status code: 128
analyze_1    | Message: "fatal: could not read Username for 'https://github.com': terminal prompts disabled"
analyze_1    | Output: "": file /home/buildnode/jenkins/workspace/oss-swift-5.2-package-linux-ubuntu-18_04/swift/stdlib/public/core/ErrorType.swift, line 200
analyze_1    | Current stack trace:
analyze_1    | 0    libswiftCore.so                    0x00007ff392e15db0 swift_reportError + 50
analyze_1    | 1    libswiftCore.so                    0x00007ff392e87f60 _swift_stdlib_reportFatalErrorInFile + 115
analyze_1    | 2    libswiftCore.so                    0x00007ff392b9cdfe <unavailable> + 1383934
analyze_1    | 3    libswiftCore.so                    0x00007ff392b9ca07 <unavailable> + 1382919
analyze_1    | 4    libswiftCore.so                    0x00007ff392b9cfe8 <unavailable> + 1384424
analyze_1    | 5    libswiftCore.so                    0x00007ff392b9b2d0 _assertionFailure(_:_:file:line:flags:) + 520
analyze_1    | 6    libswiftCore.so                    0x00007ff392be3c4c <unavailable> + 1674316
analyze_1    | 7    Run                                0x000055e446ed5f51 <unavailable> + 7941969
analyze_1    | 8    libc.so.6                          0x00007ff39086eab0 __libc_start_main + 231
analyze_1    | 9    Run                                0x000055e4468619ea <unavailable> + 1173994
analyze_1    | 0x7ff39283e88f
analyze_1    | 0x7ff392b9b4e5
analyze_1    | 0x7ff392be3c4b
analyze_1    | 0x55e446ed5f50, main at /build/<compiler-generated>:0
analyze_1    | 0x7ff39086eb96
analyze_1    | 0x55e4468619e9
analyze_1    | 0xffffffffffffffff
swiftpackageindex-server_analyze_1 exited with code 132
```

### PR DESCRIPTION
**Pull request by finestructure**
Fixes #58 

I've been processing for hours now on `spi` and it doesn't hang or crash after taking out the promtp workaround. It looks like while we fixed the hang when running directly from a terminal we traded that for a crash on Linux when there is no terminal.

Since we'll be running it in the container, this will be fine and if someone runs it interactively it'll be obvious when it's hanging.

Does that make sense?

Runtime without errors ~5.5h:

Screenshot 2020-05-12 at 18 58 05

### CODE REVIEW

File: Sources/App/Commands/Analyzer.swift [hunk 1]
```diff
@@ -123,11 +123,11 @@ func pullOrClone(application: Application, package: Package) throws -> EventLoop
             try Current.shell.run(command: .init(string: "git reset --hard"), at: cacheDir)
             let branch = package.repository?.defaultBranch ?? "master"
             try Current.shell.run(command: .gitCheckout(branch: branch), at: cacheDir)
-            try Current.shell.run(command: .gitPull(allowingPrompt: false), at: cacheDir)
+            try Current.shell.run(command: .gitPull(), at: cacheDir)
```
Comment (finestructure) [inline Sources/App/Commands/Analyzer.swift:126]: John has also merge this change upstream now, so we can easily bring it back if needed.

File: Tests/AppTests/RegressionTests.swift [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+        // unfortunately, this does *not* reproduce the hanging when prompts are allowed,
+        // presumably because the test runs without interactive terminal
+        let pkg = Package(url: "https://github.com/foo-nonexistant/bar.git")
+        let cacheDir = try XCTUnwrap(Current.fileManager.cacheDirectoryPath(for: pkg))
+        let wdir = Current.fileManager.checkoutsDirectory
+        XCTAssertThrowsError(
+            try Current.shell.run(command: .gitClone(url: URL(string: pkg.url)!, to: cacheDir), at: wdir)
+        ) { error in
+            let e = error as? ShellOutError
+            XCTAssertEqual(e?.message, "fatal: could not read Username for 'https://github.com': Device not configured")
```
Comment (finestructure) [inline Tests/AppTests/RegressionTests.swift:25]: This is key here for the diagnosis: `Device not configured`. This only happens when run via tests or in a container and that's why it crashes if you suppress the prompt in a container, I suppose.

Comment (finestructure) [reply Tests/AppTests/RegressionTests.swift:25]: BTW, I'm not sure if the test adds any value as is - it's not really testing our error case. Should I take it out?

Comment (finestructure) [reply Tests/AppTests/RegressionTests.swift]: Removed as discussed!
