### PR TITLE
Cache protected images in GitHub readme files

### LINKED ISSUE #2790: Broken README image
We do some wrangling of GitHub image URLs to make them work in SPI READMEs but there's obviously something going on here that's breaking this one:

Screenshot 2023-12-15 at 12 59 37@2x

and on GitHub:

Screenshot 2023-12-15 at 13 00 39@2x

In the GitHub page, the URL is:

```
https://private-user-images.githubusercontent.com/60271542/286382420-cf47949d-e99b-42f8-bd74-b308252edf59.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NDU1ODYsIm5iZiI6MTcwMjY0NTI4NiwicGF0aCI6Ii82MDI3MTU0Mi8yODYzODI0MjAtY2Y0Nzk0OWQtZTk5Yi00MmY4LWJkNzQtYjMwODI1MmVkZjU5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDEzMDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZTk2N2UyYjE0ZjY0OTNjNTlkNjgxZWI0ODQzZjY5MTk2ZmY2NDczNTYxNDVkZGQyZjVjMDQwZWYxMTA4MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CQn8CPtaCbrZtPYS1KpNCgnX506Xkv4V5J1hfqOWCb8
```

and in our page, the URL is:

```
https://private-user-images.githubusercontent.com/60271542/286382420-cf47949d-e99b-42f8-bd74-b308252edf59.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NDQxMDcsIm5iZiI6MTcwMjY0MzgwNywicGF0aCI6Ii82MDI3MTU0Mi8yODYzODI0MjAtY2Y0Nzk0OWQtZTk5Yi00MmY4LWJkNzQtYjMwODI1MmVkZjU5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDEyMzY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NzQ5YTZkMGM0YmJiOTE2NTJlM2YxOTljZDY0YjVjN2Q0MDE3NTdmYTcxMWRlNjRjNmYwMTM2YjQzYTYzZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2O283Gh1A5PqRJYi65hoPOuoywkibbC3pBxTA_TN8m0
```

The `jwt` is wrong in the second one. I thought that we may have just been out of sync with our README cache, but the repository hasn't been been touched in 5 days. Odd.

### PR DESCRIPTION
**Pull request by daveverwer**
Fixes #2790 

This PR scans any readme files fetched from the GitHub API that also have images that are hosted on `private-user-images.githubusercontent.com` and also have a `jwt`parameter.

The images are collected and uploaded to S3 in the same directory as the readme file is stored. They retain their filename in that directory.

Images are only uploaded if/when the `etag` of the readme itself changes, which is the behaviour it already had (also see #2937, although this should not make that worse if it even is a problem!)

### CODE REVIEW

File: Sources/App/Migrations/076/UpdateRepositoryResetReadmes.swift [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+
+struct UpdateRepositoryResetReadmes: AsyncMigration {
+    func prepare(on database: Database) async throws {
+        guard let db = database as? SQLDatabase else {
+            fatalError("Database must be an SQLDatabase ('as? SQLDatabase' must succeed)")
+        }
+
+        try await db.raw("""
+        UPDATE repositories
+        SET s3_readme = jsonb_set(s3_readme, '{cached,githubEtag}', '""', FALSE);
```
Comment (finestructure) [inline Sources/App/Migrations/076/UpdateRepositoryResetReadmes.swift:27]: This is to reset the field, isn't it? Why aren't we just setting it to `NULL`? That way we don't "bake in" any format and can be sure it's readable.

File: Sources/S3Store/S3Store.swift [hunk 2]
```diff
@@ -27,6 +27,12 @@ public struct S3Store {
     }
     
     public func save(payload: String, to key: Key) async throws {
+        guard let data = payload.data(using: .utf8)
+        else { throw Error.genericError("Could not convert readme string to data") }
+        try await save(payload: data, to: key)
```
Comment (finestructure) [inline Sources/S3Store/S3Store.swift:32]:
```suggestion
        try await save(payload: Data(payload.utf8), to: key)
```

File: Tests/AppTests/GithubTests.swift [hunk 3]
```diff
@@ -15,10 +15,12 @@
 @testable import App
 
 import Vapor
+import SwiftSoup
+import S3Store
 import XCTest
 
 
-class GithubTests: AppTestCase {
+class GithubTests: SnapshotTestCase {
```
Comment (finestructure) [inline Tests/AppTests/GithubTests.swift:23]:
```suggestion
class GithubTests: AppTestCase {
```

Class doesn't seem to have gained any snapshot tests?

File: Tests/AppTests/__Snapshots__/GithubTests/test_fetchReadme_withPrivateGitHubImages.1.txt [hunk 4]
```diff
@@ -0,0 +1,6 @@
+<html>
+ <head></head>
+ <body> 
+  <img src="https://awsReadmeBucket.s3.us-east-2.amazonaws.com/foo/bar/with-jwt.jpg" data-original-src="https://private-user-images.githubusercontent.com/with-jwt.jpg?jwt=some-jwt" /> 
+ </body>
+</html>
```
Comment (finestructure) [inline Tests/AppTests/__Snapshots__/GithubTests/test_fetchReadme_withPrivateGitHubImages.1.txt:6]: It looks like this was a snapshot for a test in `GithubTests` in an earlier version but isn't anymore? There's no `GithubTests.test_fetchReadme_withPrivateGitHubImages`.

**Review by finestructure — CHANGES_REQUESTED** [review]

File: Sources/App/Migrations/076/UpdateRepositoryResetReadmes.swift (hunk 1 above)
Comment (daveverwer) [reply Sources/App/Migrations/076/UpdateRepositoryResetReadmes.swift:27]: It's to reset just the `githubEtag` part of the JSON field. If we reset the field fully, we'll lose all README files for the duration of a full pass of ingestion as the URL to the S3 cached copy of the README is in the other part of this JSON field. 

I'd welcome verification of the SQL statement, though. I have tried it and it does what I expect it to. The `FALSE` at the end means that if there is no value for etag then it won't create it, which is also for safety around fields that do not yet have a value (for new packages yet to be ingested).

It seemed like the correct way to approach it to me.

Comment (finestructure) [reply Sources/App/Migrations/076/UpdateRepositoryResetReadmes.swift:27]: Oh, I see! That makes sense.

In that case we should put that in a test though. We have a couple that do similar things, for example `test_pending_to_triggered_migration` and `test_DeleteArmBuilds_migration`.

File: Sources/App/Core/Extensions/S3Store+ext.swift [hunk 5]
```diff
@@ -41,15 +41,41 @@ extension S3Store {
...
+        if let imageUrl {
+            guard let url = URL(string: imageUrl)
+            else { throw S3Store.Error.genericError("Invalid imageUrl \(imageUrl)") }
+            let filename = url.lastPathComponent
+            let path = "\(owner)/\(repository)/\(filename)".lowercased()
+            return .init(bucket: bucket, path: path)
+        } else {
+            let path = "\(owner)/\(repository)/readme.html".lowercased()
+            return .init(bucket: bucket, path: path)
+        }
```
[the remark this answers is not in the document]
Comment (daveverwer) [reply Sources/App/Core/Extensions/S3Store+ext.swift:79]: I don't know if I agree here. I like that the API is the same on the consumer side for both parts of this since they are so closely related. I'd certainly not call it weird

File: Tests/AppTests/__Snapshots__/GithubTests/test_fetchReadme_withPrivateGitHubImages.1.txt (hunk 4 above)
Comment (daveverwer) [reply Tests/AppTests/__Snapshots__/GithubTests/test_fetchReadme_withPrivateGitHubImages.1.txt:6]: Well spotted. Thanks

File: Sources/App/Migrations/076/UpdateRepositoryResetReadmes.swift (hunk 1 above)
Comment (daveverwer) [reply Sources/App/Migrations/076/UpdateRepositoryResetReadmes.swift:27]: Added `test_migration076_updateRepositoryResetReadmes`

**Review by finestructure — APPROVED** [review]
