### PR TITLE
Path encode reference when constructing S3 urls

### LINKED ISSUE #2287: Doc build fails for `SelectionKit` reference `feature/2.0.0`
Umbrella issue to track the full fix

- [x] doc uploader: https://github.com/SwiftPackageIndex/DocUploader/pull/11
- [x] builder: [MR 186](https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/186)
- [x] re-trigger doc build
- [x] server url

### PR DESCRIPTION
**Pull request by finestructure**
I'll manually deploy from the branch to test this on dev.

Fixes #2287

To do:

- [x] add tests

### CODE REVIEW

**Review by daveverwer — APPROVED** [review]

File: Tests/AppTests/ReferenceTests.swift [hunk 1]
```diff
@@ -34,6 +34,30 @@ class ReferenceTests: XCTestCase {
         }
     }
 
+    func test_Equatable() throws {
```
Comment (finestructure) [inline Tests/AppTests/ReferenceTests.swift:37]: I'm having second thoughts whether pushing `pathEncoded` all the way into `==` is a good idea. It may be too broad and lead to unrelated issues if users were to have distinct `feature/a` and `feature-a` branches.

It's probably better to restrict this widened equality only to the area of documentation url/target matching.

Will revisit.

**Comment by finestructure** [comment]
This is good to go now, tested against dev db-dump.
